#!/usr/bin/env python

import os
import sys
import subprocess
from io import open

# Use py.exe http://blog.python.org/2011/07/python-launcher-for-windows_11.html on Windows
PYTHON_VERSIONS = ["2.4", "2.7", "3.4"]

def compare(case, arguments=""):
    failed = False
    for pyver in PYTHON_VERSIONS:
        ext = "xlsx"
        if os.path.exists("test/%s.xlsm" % case):
            ext = "xlsm"
        left = subprocess.check_output("py -%s ./xlsx2csv.py %s test/%s.%s" %(pyver, arguments, case, ext)).decode('utf-8').replace('\r','')

        f = open("test/%s.csv" %case, "r", encoding="utf-8")
        right = f.read().replace('\r','')
        f.close()

        if left != right:
            print("FAILED: %s %s" %(case, pyver))
            print(" actual:", left.replace("\r", "\\r").replace("\n", "\\n"))
            print(" expected:", right.replace("\r", "\\r").replace("\n", "\\n"))
            failed = True
        else:
            print("OK: %s %s" %(case, pyver))
    if failed:
        sys.exit(1)

compare("datetime", "-f \"%Y-%m-%d %H:%M:%S\"")
compare("empty_row")
compare("junk-small")
compare("last-column-empty")
compare("sheets", "-a")
compare("skip_empty_lines", "-i")
compare("twolettercolumns")
compare("xlsx2csv-test-file")
compare("escape", "-e")
compare("hyperlinks", "--hyperlinks")
compare("hyperlinks_continous", "--hyperlinks")
compare("namespace")
compare("float")